name: release

on:
  push:
    tags:
      - 'v*'


jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: .
          tags: "ghcr.io/paragor/e2logs:${{ github.ref_name }}"
      - name: Replace chart tag
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/v}"
          sed -i -E "s/^version:.*/version: ${TAG}/" dist/chart/Chart.yaml
          sed -i -E "s/^appVersion:.*/appVersion: \"${TAG}\"/" dist/chart/Chart.yaml
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: .github/helm.config.yml
          charts_dir: dist
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
